/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
  @Test public void testGetImg(){
    assertEquals(100, App.getImg("C:\\Users\\PVOVi\\codefellows\\401\\bitmap-transformer\\src\\main\\resources\\mario.bmp").getHeight());
  }
}