/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import java.util.ArrayList;

public class Restaurant extends Business {

    int priceCategory;

    public Restaurant(String name, String description, int rating, int priceCategory) {
        super(name, description, rating);
        this.priceCategory = priceCategory;
    }

    ArrayList<Review> restaurantReviewList = new ArrayList<>();

    public int getPriceCategory() {
        return priceCategory;
    }

    public void setPriceCategory(int priceCategory) {
        this.priceCategory = priceCategory;
    }

    public void addReview(Review reviewToAdd) {
        restaurantReviewList.add(reviewToAdd);
        updateStarRating();
    }

    public void updateStarRating(){
        int total = 0;
        for (int i = 0; i < restaurantReviewList.size(); i++) {
            total += restaurantReviewList.get(i).stars;
        }
        int newStars = total / restaurantReviewList.size(); // is this zero based? thinking about "off by one"
        this.setRating(newStars);
    }
}
