/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.List;
import java.util.ArrayList;

public class BasicLibraryTest {

    @Test
    public void rollSomeDice() {
        Roll roll = new Roll();
        int timesToRoll = 10;
        ArrayList finalRoll = roll.diceRoll(timesToRoll);
        assertEquals(finalRoll.size(), timesToRoll);

        boolean diceNumber = false;

        for (int i = 0; i < timesToRoll; i++) { // created w help from Claudio Bailon-Schubert
            if ((int) finalRoll.get(i) > 0 && (int) finalRoll.get(i) < 7) {
                diceNumber = true;
            } else {
                diceNumber = false;
                break;
            }
        }
        assertTrue("all the numbers are on a standard 1d6", diceNumber);
    }

    @Test
    public void findDuplicates() {
        DuplicateFinder findTheDuples = new DuplicateFinder();
        Roll roll = new Roll();
        int numberOfDupleChances = 20;
        ArrayList dupleRoller = roll.diceRoll(numberOfDupleChances);
        boolean testTrue = findTheDuples.duplicatePresent(dupleRoller);

        assertTrue(testTrue);
    }

    @Test
    public void Averages() {
        Roll roll = new Roll();
        Averages thisAverage = new Averages();
        ArrayList averageToFind = roll.diceRoll(10000);
        double min = 0;
        double max = 6;
        double numberAverage = (max - min) / 2;

        double averageToTest = thisAverage.averageFinder(averageToFind);
        boolean correctAverage;

        if (averageToTest > numberAverage - 1 && averageToTest < numberAverage + 1) {
            correctAverage = true;
        } else {
            correctAverage = false;
        }

        System.out.println(numberAverage);
        System.out.println(averageToTest);
        assertTrue("it is within the average", correctAverage);
    }

    @Test
    public void LowestAverage() {
        int[][] weeklyMonthTemperatures = {
          {66, 64, 58, 65, 71, 57, 60},
          {57, 65, 65, 70, 72, 65, 51},
          {5, 4, 6, 3, 9, 7, 1},
          {65, 56, 55, 52, 55, 62, 57}
        };

        LowestAverage lowLow = new LowestAverage();
        int[] testLowAverage = {5, 4, 6, 3, 9, 7, 1};
        int[] toTest = lowLow.lowAverage(weeklyMonthTemperatures);
        assertArrayEquals(testLowAverage, toTest);
    }

    @Test public void missingTemp () {
        Maps bananaWeather = new Maps();

        int[][] weeklyMonthTemperatures = {
          {66, 64, 58, 65, 71, 57, 60},
          {57, 65, 65, 70, 72, 65, 51},
          {55, 54, 60, 53, 59, 57, 61},
          {65, 56, 55, 52, 55, 62, 57}
        };
        String bananaResult = bananaWeather.weatherReport(weeklyMonthTemperatures);

        String testString = "High: 72\nLow: 51\nNever saw temperature: 63\nNever saw temperature: 67\nNever saw temperature: 68\nNever saw temperature: 69";
        assertEquals(testString, bananaResult);
    }

    @Test public void electionTally () {
        List<String> votes = new ArrayList<>();
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Bush");
        votes.add("Shrub");
        votes.add("Hedge");
        votes.add("Shrub");
        votes.add("Bush");
        votes.add("Hedge");
        votes.add("Bush");

        Maps voteCounter = new Maps();

        String winner = "Bush received the most votes!";

        assertEquals(winner, voteCounter.tally(votes));
    }
}